### ISSUE TITLE
Testing/debuggin requests and zipfile implementation 

### ISSUE THREAD

**Issue by lfnothias** [lfnothias/vm-NAP#3]
First locally, then push changes to the repo and will test on streamlit community webapp.

**Comment by lucaspradi** [comment]
Fixed locally. Still need to be tested on the community webapp

**Comment by lfnothias** [comment]
Merged in https://github.com/lfnothias/vm-NAP/pull/5

**Comment by lucaspradi** [comment]
No more problems regarding request and zipfile
